@api = http://localhost:3000


POST {{api}}
Cache-Control: no-cache
Content-Type: application/json

{
  "author": "Mary Doe",
  "title": "gRPC with Go for beginners",
  "description": "description...",
  "rate": 5
}

